const $=id=>document.getElementById(id);
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[13.25,47.45],zoom:8,attributionControl:true});
map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');

let vectorSource=null,gps=null,gpsMarker=null,searchMarker=null;
let routeCoords=null,routeName='',routeBaseName='',routeOptions=[],selectedRouteIndex=0;
let customStart=null,customStartName='';
let planning=false,pickMode=null,planStart=null,planWays=[],planGoal=null,planMarkers=[];
const markers={alms:[],huts:[],food:[],peaks:[]};
let poiRefreshTimer=null,searchTimer=null;
let watchId=null,trackPts=[],trackKm=0,tracking=false,paused=false,trackStartedAt=0,elapsedMs=0,timerId=null,liveMarker=null,skipDistanceOnce=false,followMode=true;

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function geoKm(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function bearing(a,b){const p1=a[1]*Math.PI/180,p2=b[1]*Math.PI/180,d=(b[0]-a[0])*Math.PI/180,y=Math.sin(d)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(d);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function fmtTime(h){if(!Number.isFinite(h)||h<=0)return'—';const m=Math.round(h*60),hh=Math.floor(m/60),mm=m%60;return hh?`${hh} h ${mm?mm+' min':''}`:`${mm} min`}
function clearMarkers(cat){markers[cat].forEach(m=>m.remove());markers[cat]=[]}
function visible(cat){return $(cat==='alms'?'almsChk':cat==='huts'?'hutsChk':cat==='food'?'foodChk':'peaksChk').checked}

function classify(f,layer){const p=f.properties||{},name=p.name||p.name_de||p['name:de']||'',cls=String(p.class||'').toLowerCase(),sub=String(p.subclass||'').toLowerCase();if(layer==='mountain_peak')return name?['peaks','Gipfel']:null;if(layer==='place'&&name&&/(alm|alpe|hütte|huette|berggasthaus|jausen)/i.test(name))return['alms','Alm / Alpe'];if(layer==='poi'){if(['alpine_hut','wilderness_hut'].includes(sub)||/hut/.test(sub))return['huts','Hütte'];if((['restaurant','cafe','fast_food','bar','biergarten'].includes(sub)||['restaurant','cafe','bar'].includes(cls))&&/(alm|alpe|hütte|huette|berg|jausen)/i.test(name))return['food','Berggasthaus / Einkehr'];if(/(alm|alpe)/i.test(name))return['alms','Alm / Alpe']}return null}
function featureCoord(f){if(!f.geometry)return null;if(f.geometry.type==='Point')return f.geometry.coordinates;if(f.geometry.type==='MultiPoint')return f.geometry.coordinates[0];return null}
function popupHtml(name,type){return `<b>${esc(name)}</b><br>${esc(type)}<button class="popbtn fromBtn secondary">Von hier starten</button><button class="popbtn routeBtn good">Wanderroute hierher</button>`}
function addPoi(cat,type,name,c,seen){const key=cat+'|'+name+'|'+c[0].toFixed(5)+'|'+c[1].toFixed(5);if(seen.has(key))return;seen.add(key);const el=document.createElement('div');el.className='poi-marker poi-'+(cat==='alms'?'alm':cat==='huts'?'hut':cat==='food'?'food':'peak');const m=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(c).addTo(map);markers[cat].push(m);if(!visible(cat))el.style.display='none';el.addEventListener('click',ev=>{ev.stopPropagation();const pop=new maplibregl.Popup({offset:14}).setLngLat(c).setHTML(popupHtml(name,type)).addTo(map);setTimeout(()=>{const root=pop.getElement();root?.querySelector('.fromBtn')?.addEventListener('click',()=>{customStart=c;customStartName=name;$('status').textContent='Start gesetzt: '+name;pop.remove()});root?.querySelector('.routeBtn')?.addEventListener('click',()=>routeTo(c,name))},0)})}
function updatePois(){if(!vectorSource)return;const closeZoom=map.getZoom()>=11;Object.keys(markers).forEach(clearMarkers);const seen=new Set();for(const layer of ['poi','place','mountain_peak']){let fs=[];try{fs=map.querySourceFeatures(vectorSource,{sourceLayer:layer})||[]}catch{continue}for(const f of fs){const cl=classify(f,layer),c=featureCoord(f);if(!cl||!c)continue;if(!closeZoom&&cl[0]!=='alms')continue;const n=f.properties?.name||f.properties?.name_de||f.properties?.['name:de']||'Ohne Namen';addPoi(cl[0],cl[1],n,c,seen);if(seen.size>400)break}}if(!tracking&&!planning)$('status').textContent=closeZoom?`${markers.alms.length} Almen · ${markers.huts.length} Hütten · ${markers.food.length} Einkehr · ${markers.peaks.length} Gipfel`:`${markers.alms.length} Almen · weitere Ziele beim Hineinzoomen`}

map.on('load',()=>{const sources=map.getStyle().sources;vectorSource=Object.keys(sources).find(k=>sources[k].type==='vector')||null;
 map.addSource('hiking',{type:'raster',tiles:['https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png'],tileSize:256});map.addLayer({id:'hiking',type:'raster',source:'hiking',paint:{'raster-opacity':.78}});
 map.addSource('alternatives',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'alternative-hit',type:'line',source:'alternatives',paint:{'line-width':18,'line-opacity':0,'line-color':'#777'}});map.addLayer({id:'alternative-lines',type:'line',source:'alternatives',paint:{'line-width':6,'line-color':'#777','line-opacity':.72,'line-dasharray':[1.2,1.2]}});
 map.addSource('route',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'route-outline',type:'line',source:'route',paint:{'line-width':10,'line-color':'#fff','line-opacity':.95}});map.addLayer({id:'route-line',type:'line',source:'route',paint:{'line-width':6,'line-color':'#7a24b8','line-opacity':1}});
 map.addSource('route-arrows',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'route-arrows',type:'symbol',source:'route-arrows',layout:{'text-field':'➤','text-size':20,'text-rotate':['get','bearing'],'text-rotation-alignment':'map','text-allow-overlap':true},paint:{'text-color':'#7a24b8','text-halo-color':'#fff','text-halo-width':2}});
 map.addSource('track',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'track-line',type:'line',source:'track',paint:{'line-width':5,'line-color':'#176b36','line-opacity':1}});
 $('status').textContent=vectorSource?'Live-Karte geladen. Almen bleiben in jeder Zoomstufe sichtbar.':'Kartendaten konnten nicht gelesen werden.'});
map.on('idle',()=>{clearTimeout(poiRefreshTimer);poiRefreshTimer=setTimeout(updatePois,250)});
map.on('dragstart',()=>{if(tracking&&followMode)setFollowMode(false)});
map.on('mouseenter','alternative-hit',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','alternative-hit',()=>map.getCanvas().style.cursor='');map.on('click','alternative-hit',e=>{const idx=Number(e.features?.[0]?.properties?.optionIndex);if(Number.isInteger(idx))selectRouteOption(idx,true)});
map.on('click',e=>{if(!planning||!pickMode)return;const c=[e.lngLat.lng,e.lngLat.lat];if(pickMode==='start')planStart=c;else if(pickMode==='via')planWays.push(c);else if(pickMode==='goal')planGoal=c;pickMode=null;refreshPlanMarkers();refreshPlanText();$('status').textContent='Punkt gesetzt.'});

$('routesChk').addEventListener('change',e=>{if(map.getLayer('hiking'))map.setLayoutProperty('hiking','visibility',e.target.checked?'visible':'none')});['alms','huts','food','peaks'].forEach(cat=>{const id=cat==='alms'?'almsChk':cat==='huts'?'hutsChk':cat==='food'?'foodChk':'peaksChk';$(id).addEventListener('change',()=>markers[cat].forEach(m=>m.getElement().style.display=$(id).checked?'block':'none'))});

function requestLocation(cb=null){if(!navigator.geolocation){$('status').textContent='Standort nicht unterstützt.';return}if(!window.isSecureContext){$('status').textContent='Standort benötigt HTTPS.';return}$('status').textContent='Standortfreigabe wird angefragt …';navigator.geolocation.getCurrentPosition(p=>{gps=[p.coords.longitude,p.coords.latitude];if(gpsMarker)gpsMarker.remove();const el=document.createElement('div');el.style.cssText='width:18px;height:18px;border-radius:50%;background:#1769d2;border:3px solid white;box-shadow:0 1px 5px #555';gpsMarker=new maplibregl.Marker({element:el}).setLngLat(gps).addTo(map);map.flyTo({center:gps,zoom:15});$('status').textContent=`Standort aktiv · ± ${Math.round(p.coords.accuracy||0)} m`;if(cb)cb()},e=>{$('status').textContent=e.code===1?'Standort nicht erlaubt.':'Standort konnte nicht bestimmt werden.'},{enableHighAccuracy:true,timeout:15000,maximumAge:5000})}
$('gpsBtn').addEventListener('click',()=>requestLocation());

function analyzeCoords(c){let dist=0,up=0;const remDist=new Array(c.length).fill(0),remUp=new Array(c.length).fill(0);for(let i=c.length-2;i>=0;i--){const d=geoKm({lat:c[i][1],lng:c[i][0]},{lat:c[i+1][1],lng:c[i+1][0]});let dz=0;if(c[i].length>2&&c[i+1].length>2){const z=+c[i+1][2]-+c[i][2];if(Number.isFinite(z)&&z>0)dz=z}remDist[i]=remDist[i+1]+d;remUp[i]=remUp[i+1]+dz}dist=remDist[0];up=remUp[0];return{dist,up,effort:dist+up/120,remDist,remUp,time:dist/5+up/600}}
function routeStats(f){const c=f.geometry.coordinates,a=analyzeCoords(c),p=f.properties||{},pl=Number(p['track-length']||p.distance||p.length),pa=Number(p['filtered ascend']||p.filtered_ascend||p.ascend||p.ascent);if(Number.isFinite(pl)&&pl>0)a.dist=pl>1000?pl/1000:pl;if(Number.isFinite(pa)&&pa>=0)a.up=pa;a.effort=a.dist+a.up/120;a.time=a.dist/5+a.up/600;return{coords:c,...a}}
function routeFingerprint(c){if(!c?.length)return'';const picks=[c[0],c[Math.floor(c.length*.25)],c[Math.floor(c.length*.5)],c[Math.floor(c.length*.75)],c[c.length-1]];return picks.map(p=>`${(+p[0]).toFixed(4)},${(+p[1]).toFixed(4)}`).join('|')}
async function fetchRouteOption(points,idx){const lonlats=points.map(p=>`${p[0]},${p[1]}`).join('|'),url='https://brouter.de/brouter?lonlats='+encodeURIComponent(lonlats)+`&profile=trekking&alternativeidx=${idx}&format=geojson`;const r=await fetch(url);if(!r.ok)throw new Error('routing');const d=await r.json(),f=d.type==='FeatureCollection'?d.features?.[0]:d;if(!f?.geometry?.coordinates?.length)throw new Error('empty');const s=routeStats(f);return{...s,brouterIndex:idx,fingerprint:routeFingerprint(s.coords)}}
function arrowFeatures(c){const fs=[];let acc=0;for(let i=1;i<c.length;i++){acc+=geoKm({lat:c[i-1][1],lng:c[i-1][0]},{lat:c[i][1],lng:c[i][0]});if(acc>=.28){fs.push({type:'Feature',properties:{bearing:bearing(c[i-1],c[i])},geometry:{type:'Point',coordinates:c[i]}});acc=0}}return{type:'FeatureCollection',features:fs}}
function renderRouteOptions(){if(!map.getSource('alternatives'))return;const features=routeOptions.map((o,i)=>({type:'Feature',properties:{optionIndex:i},geometry:{type:'LineString',coordinates:o.coords}})).filter((_,i)=>i!==selectedRouteIndex);map.getSource('alternatives').setData({type:'FeatureCollection',features})}
function showRoute(fit=true){if(!routeCoords?.length||!map.getSource('route'))return;map.getSource('route').setData({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:routeCoords}});map.getSource('route-arrows')?.setData(arrowFeatures(routeCoords));renderRouteOptions();['alternative-hit','alternative-lines','route-outline','route-line','route-arrows'].forEach(id=>{if(map.getLayer(id))map.moveLayer(id)});if(fit){const b=new maplibregl.LngLatBounds();routeOptions.forEach(o=>o.coords.forEach(x=>b.extend(x)));map.fitBounds(b,{padding:{top:120,bottom:200,left:35,right:35},duration:700})}}
function updateRouteInfo(o){$('routeRemain').textContent=o.dist.toFixed(1)+' km';$('routeEffort').textContent=o.effort.toFixed(1)+' km';$('routeRemainUp').textContent=Math.round(o.up)+' hm';$('routeText').textContent=`${o.dist.toFixed(1)} km · ca. ${fmtTime(o.time)} · ${Math.round(o.up)} hm ↑${routeOptions.length>1?` · ${routeOptions.length} Varianten`:''}`}
function selectRouteOption(index,fromTap=false){const o=routeOptions[index];if(!o||tracking)return;selectedRouteIndex=index;routeCoords=o.coords;routeName=routeBaseName+(routeOptions.length>1?` · Route ${index+1}`:'');showRoute(true);$('routeTitle').textContent=routeName;updateRouteInfo(o);$('status').textContent=fromTap?'Alternative ausgewählt.':'Route ausgewählt.'}
async function calculateRoutes(points,baseName){$('status').textContent='Berechne Wanderroute und Alternativen …';routeOptions=[];const settled=await Promise.allSettled([0,1,2].map(i=>fetchRouteOption(points,i))),seen=new Set();for(const r of settled){if(r.status!=='fulfilled')continue;const o=r.value;if(seen.has(o.fingerprint))continue;seen.add(o.fingerprint);routeOptions.push(o)}if(!routeOptions.length)throw new Error('none');routeBaseName=baseName;selectedRouteIndex=0;selectRouteOption(0,false);$('routeInfo').style.display='block';$('status').textContent=routeOptions.length>1?`${routeOptions.length} Routen gefunden. Graue Alternative antippen.`:'Route berechnet und angezeigt.'}
async function routeTo(target,name){const start=customStart||gps;if(!start){requestLocation(()=>routeTo(target,name));return}try{await calculateRoutes([start,target],(customStartName||'Standort')+' → '+name)}catch{$('status').textContent='Routing derzeit nicht erreichbar.'}}
$('clearRoute').addEventListener('click',()=>{if(tracking)return;routeCoords=null;routeName='';routeBaseName='';routeOptions=[];selectedRouteIndex=0;customStart=null;customStartName='';$('routeInfo').style.display='none';map.getSource('route')?.setData({type:'FeatureCollection',features:[]});map.getSource('alternatives')?.setData({type:'FeatureCollection',features:[]});map.getSource('route-arrows')?.setData({type:'FeatureCollection',features:[]});$('status').textContent='Route gelöscht.'});

function clearPlanMarkers(){planMarkers.forEach(m=>m.remove());planMarkers=[]}
function planMarker(c,label){const el=document.createElement('div');el.style.cssText='width:28px;height:28px;border-radius:50%;background:white;border:3px solid #1769d2;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:12px;box-shadow:0 1px 6px #555';el.textContent=label;planMarkers.push(new maplibregl.Marker({element:el}).setLngLat(c).addTo(map))}
function refreshPlanMarkers(){clearPlanMarkers();if(planStart)planMarker(planStart,'S');planWays.forEach((c,i)=>planMarker(c,String(i+1)));if(planGoal)planMarker(planGoal,'Z')}
function refreshPlanText(){$('planStartText').textContent='Start: '+(planStart?'gesetzt':'noch nicht gewählt');$('planViaText').textContent='Zwischenpunkte: '+planWays.length;$('planGoalText').textContent='Ziel: '+(planGoal?'gesetzt':'noch nicht gewählt')}
function openPlanner(){if(tracking)return;planning=true;pickMode=null;$('planPanel').style.display='block';$('routeInfo').style.display='none';refreshPlanText();$('status').textContent='Route planen: Start und Ziel wählen.'}
$('planBtn').addEventListener('click',openPlanner);$('planCancel').addEventListener('click',()=>{planning=false;pickMode=null;$('planPanel').style.display='none';clearPlanMarkers();$('status').textContent='Planung geschlossen.'});
$('planGps').addEventListener('click',()=>{const done=()=>{planStart=[...gps];refreshPlanMarkers();refreshPlanText()};gps?done():requestLocation(done)});
$('planStartMap').addEventListener('click',()=>{pickMode='start';$('status').textContent='Auf Karte tippen: Start.'});$('planVia').addEventListener('click',()=>{pickMode='via';$('status').textContent='Auf Karte tippen: Zwischenpunkt.'});$('planGoal').addEventListener('click',()=>{pickMode='goal';$('status').textContent='Auf Karte tippen: Ziel.'});
$('planCalc').addEventListener('click',async()=>{if(!planStart||!planGoal){alert('Bitte Start und Ziel setzen.');return}try{const pts=[planStart,...planWays,planGoal];await calculateRoutes(pts,'Geplante Wanderung');planning=false;pickMode=null;$('planPanel').style.display='none';clearPlanMarkers()}catch{$('status').textContent='Routing derzeit nicht erreichbar.'}});

function nearestRouteIndex(pos){if(!routeCoords?.length)return 0;let best=0,bestD=Infinity;for(let i=0;i<routeCoords.length;i++){const d=geoKm({lat:pos[1],lng:pos[0]},{lat:routeCoords[i][1],lng:routeCoords[i][0]});if(d<bestD){bestD=d;best=i}}return best}
function remainingAt(pos){const o=routeOptions[selectedRouteIndex];if(!o)return null;const i=nearestRouteIndex(pos),dist=o.remDist[i]??0,up=o.remUp[i]??0;return{index:i,dist,up,effort:dist+up/120}}
function nextDirection(pos,idx){if(!routeCoords?.length)return null;let j=Math.min(idx+1,routeCoords.length-1),d=0;while(j<routeCoords.length-1&&d<.05){d=geoKm({lat:pos[1],lng:pos[0]},{lat:routeCoords[j][1],lng:routeCoords[j][0]});j++}const target=routeCoords[Math.max(idx+1,j-1)]||routeCoords[routeCoords.length-1];return bearing(pos,target)}
function renderRemaining(pos){const r=remainingAt(pos);if(!r)return;$('trackRemain').textContent=r.dist.toFixed(1)+' km';$('trackEffort').textContent=r.effort.toFixed(1)+' km';$('trackUp').textContent=Math.round(r.up)+' hm';const b=nextDirection(pos,r.index);if(b!=null){$('directionArrow').style.transform=`rotate(${b-map.getBearing()}deg)`;$('directionText').textContent=r.dist<.05?'Ziel erreicht':`noch ${r.dist.toFixed(1)} km`}}
function renderElapsed(){const ms=elapsedMs+(tracking&&!paused?Date.now()-trackStartedAt:0),sec=Math.floor(ms/1000),m=Math.floor(sec/60),s=sec%60;$('trackTime').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function setFollowMode(on){followMode=!!on;$('followMe').classList.toggle('active',followMode);if(followMode&&gps)map.easeTo({center:gps,zoom:Math.max(map.getZoom(),15),duration:300})}
$('followMe').addEventListener('click',()=>setFollowMode(!followMode));$('northUp').addEventListener('click',()=>map.easeTo({bearing:0,pitch:0,duration:350}));
function setTrackingChrome(active){$('navControls').style.display=active?'flex':'none';$('directionCard').style.display=active?'block':'none';$('top').style.display=active?'none':'flex';$('filters').style.display=active?'none':'flex'}
function startTracking(){if(!routeCoords?.length){alert('Bitte zuerst eine Route berechnen.');return}if(tracking)return;if(!navigator.geolocation||!window.isSecureContext){alert('Tracking benötigt Standortzugriff über HTTPS.');return}tracking=true;paused=false;skipDistanceOnce=false;trackPts=[];trackKm=0;elapsedMs=0;trackStartedAt=Date.now();setFollowMode(true);setTrackingChrome(true);$('routeInfo').style.display='none';$('trackPanel').style.display='block';$('trackTitle').textContent=routeName||'Aktive Route';$('trackDist').textContent='0.00 km';$('trackTime').textContent='00:00';$('pauseTrack').textContent='Pause';$('pauseTrack').style.display='block';$('stopTrack').style.display='block';$('saveTrack').style.display='none';map.getSource('alternatives')?.setData({type:'FeatureCollection',features:[]});map.getSource('track')?.setData({type:'FeatureCollection',features:[]});const o=routeOptions[selectedRouteIndex];if(o){$('trackRemain').textContent=o.dist.toFixed(1)+' km';$('trackEffort').textContent=o.effort.toFixed(1)+' km';$('trackUp').textContent=Math.round(o.up)+' hm'}watchId=navigator.geolocation.watchPosition(p=>{const c=[p.coords.longitude,p.coords.latitude];gps=c;if(liveMarker)liveMarker.remove();const el=document.createElement('div');el.style.cssText='width:20px;height:20px;border-radius:50%;background:#1769d2;border:3px solid white;box-shadow:0 1px 6px #555';liveMarker=new maplibregl.Marker({element:el}).setLngLat(c).addTo(map);renderRemaining(c);if(followMode)map.easeTo({center:c,zoom:Math.max(map.getZoom(),15),duration:350});if(paused)return;const prev=trackPts[trackPts.length-1];if(prev&&!skipDistanceOnce){const d=geoKm({lat:prev[1],lng:prev[0]},{lat:c[1],lng:c[0]});if(d<.2)trackKm+=d}trackPts.push(c);skipDistanceOnce=false;$('trackDist').textContent=trackKm.toFixed(2)+' km';if(map.getSource('track')){if(trackPts.length>=2)map.getSource('track').setData({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:trackPts}})}},e=>{if(e.code===1)alert('Standort wurde nicht erlaubt.')},{enableHighAccuracy:true,maximumAge:1000,timeout:15000});timerId=setInterval(renderElapsed,1000);$('status').textContent='Live-Tracking läuft.'}
$('startRoute').addEventListener('click',startTracking);$('pauseTrack').addEventListener('click',()=>{if(!tracking)return;if(!paused){elapsedMs+=Date.now()-trackStartedAt;paused=true;$('pauseTrack').textContent='Weiter';$('status').textContent='Tracking pausiert.'}else{paused=false;skipDistanceOnce=true;trackStartedAt=Date.now();$('pauseTrack').textContent='Pause';$('status').textContent='Tracking läuft weiter.'}});$('stopTrack').addEventListener('click',()=>{if(!tracking)return;if(!paused)elapsedMs+=Date.now()-trackStartedAt;tracking=false;paused=false;if(watchId!=null)navigator.geolocation.clearWatch(watchId);watchId=null;if(timerId)clearInterval(timerId);timerId=null;renderElapsed();setTrackingChrome(false);$('pauseTrack').style.display='none';$('stopTrack').style.display='none';$('saveTrack').style.display='block';$('status').textContent='Tour beendet. Jetzt speichern.'});
function xmlEsc(s=''){return String(s).replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]))}
$('saveTrack').addEventListener('click',()=>{if(trackPts.length<2){alert('Noch keine ausreichende GPS-Spur zum Speichern.');return}const name=(routeName||'MiniTrack Tour').replace(/[\\/:*?"<>|]+/g,'-'),pts=trackPts.map(c=>`<trkpt lat="${c[1]}" lon="${c[0]}"></trkpt>`).join(''),gpx=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="MiniTrack" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${xmlEsc(name)}</name></metadata><trk><name>${xmlEsc(name)}</name><trkseg>${pts}</trkseg></trk></gpx>`,blob=new Blob([gpx],{type:'application/gpx+xml'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'.gpx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='GPX gespeichert.'});

async function searchSuggestions(text){if(text.length<2){$('suggestions').style.display='none';return}try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=6&addressdetails=1&accept-language=de&q='+encodeURIComponent(text)),d=await r.json();$('suggestions').innerHTML='';d.forEach(i=>{const row=document.createElement('div');row.className='sug';const n=i.name||i.display_name.split(',')[0];row.innerHTML=`<b>${esc(n)}</b><small>${esc(i.display_name)}</small>`;row.addEventListener('click',()=>{q.value=n;$('suggestions').style.display='none';showSearch(i,n)});$('suggestions').appendChild(row)});$('suggestions').style.display=d.length?'block':'none'}catch{$('suggestions').style.display='none'}}
const q=$('q');q.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchSuggestions(q.value.trim()),250)});function showSearch(i,n){const c=[+i.lon,+i.lat];if(searchMarker)searchMarker.remove();const el=document.createElement('div');el.className='poi-marker';el.style.background='#7d3fb2';searchMarker=new maplibregl.Marker({element:el}).setLngLat(c).addTo(map);map.flyTo({center:c,zoom:15});el.addEventListener('click',()=>{const pop=new maplibregl.Popup({offset:14}).setLngLat(c).setHTML(popupHtml(n,'Suchtreffer')).addTo(map);setTimeout(()=>{const root=pop.getElement();root?.querySelector('.fromBtn')?.addEventListener('click',()=>{customStart=c;customStartName=n;$('status').textContent='Start gesetzt: '+n;pop.remove()});root?.querySelector('.routeBtn')?.addEventListener('click',()=>routeTo(c,n))},0)})}
$('searchBtn').addEventListener('click',async()=>{const s=q.value.trim();if(!s)return;try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&addressdetails=1&accept-language=de&q='+encodeURIComponent(s)),d=await r.json();if(d.length)showSearch(d[0],d[0].name||d[0].display_name.split(',')[0]);else $('status').textContent='Nichts gefunden.'}catch{$('status').textContent='Suche nicht erreichbar.'}});q.addEventListener('keydown',e=>{if(e.key==='Enter')$('searchBtn').click()});